### ISSUE TITLE
Handle Float types in calcPerSegmentStatsTiled

### ISSUE THREAD

**Issue by petescarth** [ubarsc/pyshepseg#9]
calcPerSegmentStatsTiled works really well, but when presented with Float type data will complete without warning and produce inconsistent output, particularly when there are values between -1 and 1.

It might be useful to catch float type inputs and display a warning before they are cast to integer.

**Comment by gillins** [comment]
@neilflood I spent a fair but of time trying to convert between the numpy and numba type systems but there didn't seem to be an easy way to do that. Maybe I could just check if input is int or float then use int64 for all ints or float64 for all floats?

**Comment by petescarth** [comment]
Completely agree with the trap and warn approach - I can't even imagine how this could work on floats!

**Comment by gillins** [comment]
OK just had a another look through this and agree doing types dynamically doesn't seem to be possible here. I did hope if you image was 8 bit we didn't waste memory with int64 keys but I think we are up against a limit of the numba design with having to declare this ahead of time.

Will put in a PR to trap the float case. Would it be a [warning](https://docs.python.org/3/library/warnings.html), or an error? Noting that a warning only gets seen when running Python in development mode now... I could just `print()` something instead I guess.

**Comment by petescarth** [comment]
I vote warning, or just a print()... It will still work if float but output may not be as expected.

**Comment by neilflood** [comment]
Oh, thanks, that would be great. I was mentally adding it to my to-do list.

Just after line 791, when the image file has just been opened. Check the datatype, and if it is float, print a warning message to stderr and return immediately. Warning should say that the calcPerSegmentStatsTiled() routine cannot work with float data, and nothing has been done. 

I don't see any value in making it an exception, and as you say, the official warning function is now kind of silly.

**Comment by gillins** [comment]
Not sure I agree. I think it should either raise an exception if it isn't going to process the file so the user's script doesn't continue on expecting an output. Or print a warning and continue to process the image. 

I've gone for the former in #10. Let me know what you think.

**Comment by neilflood** [comment]
I am fine with that, too. Merge at will. Thank you.

**Comment by gillins** [comment]
Yeah the more I think about it, the more I think raising an exception is the best option here. We are casting everything to int64 so we can't even pretend we are doing something useful with the data. I think having a warning isn't really sufficient - we need to throw if back to the user to scale or whatever.

**Comment by gillins** [comment]
Totally as an aside, there is a function to infer the numba type from a numpy dype (https://numba.readthedocs.io/en/0.52.0/reference/types.html#numba.from_dtype). I'm sure this can't have been there when we were writing this because I spent ages looking for such a thing....

Also, the docstring on jitclass is illuminating as it appears you can use it as a function. So, if we were to need to do this properly we could remove `numbaTypeForImageType` and use `from_dtype` to get types for creating dictionaries in `@njit` code. We could also wrap creation of `SegmentStats` and `RatPage` in factory methods to create the correct `spec` for given numpy types.

Not that I'm suggesting we change anything right now, but I'm just jotting this down in case we need to do something like this in future....
